### ISSUE TITLE
Maya Run Plug Error

### ISSUE THREAD

**Issue by tecnnt** [gameboy12615/MMD4Maya#8]
// Error: file: F:/Apply/Maya/Maya2022/scripts/others/pluginWin.mel line 316: ModuleNotFoundError: file F:\Apply\Maya\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py line 142: No module named 'pymel' // 
// Warring: file: F:/Apply/Maya/Maya2022/scripts/others/pluginWin.mel line 316: Failed to run file: F:/Apply/Maya/Maya2022/bin/plug-ins/MMD4Maya.py // 
// Error: file: F:/Apply/Maya/Maya2022/scripts/others/pluginWin.mel line 316:  (MMD4Maya) // 

What do I need to do?
Ver:Maya2022

**Comment by Iseason2000** [comment]
Maya 2022 starts in Python 3 mode by default.
It can be switched to Python 2 mode by either using the -pythonver 2 option when starting Maya
like this 
![image](https://user-images.githubusercontent.com/65019366/141135813-765d53eb-6a40-4773-aa3e-71e0ef6b985e.png)

**Comment by gameboy12615** [comment]
@Iseason2000 我是用maya2022自带的python3

**Comment by gameboy12615** [comment]
@tecnnt sorry, I have no idea, I have never met such a problem. It seems not the problem of this plugin.
you can google: Error: file: F:/Apply/Maya/Maya2022/scripts/others/pluginWin.mel line 316: ModuleNotFoundError: file

**Comment by gameboy12615** [comment]
@tecnnt sorry, I have no idea, I have never met such a problem. It seems not the problem of this plugin.
you can google: Error: file: F:/Apply/Maya/Maya2022/scripts/others/pluginWin.mel line 316: ModuleNotFoundError: file

**Comment by sproudy** [comment]
You must have mayapy installed to able to run MMD4Maya with python3.
For some reason Maya didn't help to check the box for installing PyMEL during installation.

Fix
1. Run CMD.exe with admin 
2. Run this code
"C:\Program Files\Autodesk\Maya2022\bin\mayapy.exe" -m pip install --user pymel
3. After finish installing, you can run MMD4Maya on Maya Python3 by default.

Alternative Fix
1. Uninstall Maya 2022
2. Install Maya 2022 with PyMel checkbox checked.
3. Run MMD4Maya.
